### ISSUE TITLE
Should projects that are no longer actively developed be removed?

### ISSUE THREAD

**Issue by radumas** [mapbox/awesome-vector-tiles#26]
I investigated PGRestAPI from this list because it seemed promising for my application until I came to [this issue](https://github.com/spatialdev/PGRestAPI/issues/142) where the project maintainer replied  
>I am no longer actively developing PGRestAPI.

**Comment by stirringhalo** [comment]
I think they should be removed.

**Comment by mapsam** [comment]
Hey @radumas @stirringhalo just added a ⚠️ note to PGRestAPI in #38 - will keep this workflow for now for posterity.

**Comment by radumas** [comment]
Cool. I'll open an issue and PR with similar format if I find similar dormant repositories.
Not sure why I opened multiple issues, sorry about that.
