### ISSUE TITLE
[ADVICE] self generating, hosting and serving vector tiles

### ISSUE THREAD

**Issue by cyrilchapon** [mapbox/awesome-vector-tiles#35]
Hey,

Fresh noob to the vector tiles environement,  I'd like to find advices on which tools / standards / specs to follow on a mapbox context.

I'm willing to self generate, host and serve vector tiles, though, there's a plenty of tools / specs / formats available, and I don't know where to start.

This may not be the location where to ask this question, so I posted a question on [gis.stackexchange here](https://gis.stackexchange.com/questions/255926/self-hosting-vector-tiles) to reduntate, but I think an answer landing here could help many of us, so I'm opening this ticket :)

**Comment by cyrilchapon** [comment]
Question redundated on [tilelive repo](https://github.com/mapbox/tilelive/issues/202)

**Comment by mapsam** [comment]
Hi @cyrilchapon thanks for your question! This is a great place to ask. Looks like you got some answers in https://gis.stackexchange.com/a/255946 but seeing ...

> Do you know any node.js-based Tippecanoe alternatives ?

Check out [mapbox-tile-copy](https://github.com/mapbox/mapbox-tile-copy) which can be used as a CLI or in a Node.js application for copying from a data file source to an s3 location via [tilelive](https://github.com/mapbox/tilelive). If s3 isn't going to work, you should have a look at [node-mapnik](https://github.com/mapnik/node-mapnik) as direct tool for creating individual tiles from datasources, and putting those tiles where you need them.

Depending on your data sources and the degree of customization you're looking for (in terms of simplifying, cutting, and encoding vector tiles) these tools should give you some flexibility. If you're looking for pure-js solutions I recommend [geojson-vt](https://github.com/mapbox/geojson-vt) for encoding and [vector-tile-js](https://github.com/mapbox/vector-tile-js/) for decoding.

Cheers!
